source 'https://rubygems.org'
gem 'dm-sqlite-adapter'
gem 'data_mapper'
gem 'tvdb_party'
gem 'pry'
gem 'awesome_print'
gem 'sqlite3'
gem 'trans-api', github: "dblommesteijn/trans-api"
gem 'feedjira'
gem 'logging'
